### ISSUE TITLE
Python script not opening

### ISSUE THREAD

**Issue by awake12** [hjstn/miniDjiController#3]
When i double click the main.py it opens and closes.i triend opening it from the cmd with no success it gives me ;
usage: main.py [-h] -p PORT [-d DEVICE] [-i [INVERT [INVERT ...]]]
main.py: error: the following arguments are required: -p/--port

**Comment by hjstn** [comment]
You have to specify the COM port the controller is connected on.

**Comment by dekid69** [comment]
> You have to specify the COM port the controller is connected on.

i have similar problem it said this
Traceback (most recent call last):
  File "C:\Users\deboi\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in <module>
    import serial, pyvjoy, argparse
ModuleNotFoundError: No module named 'serial'

**Comment by hjstn** [comment]
> > You have to specify the COM port the controller is connected on.
> 
> i have similar problem it said this
> Traceback (most recent call last):
> File "C:\Users\deboi\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in 
> import serial, pyvjoy, argparse
> ModuleNotFoundError: No module named 'serial'

Did you run `pip install` in the directory to install requirements?

**Comment by deboi238** [comment]
> > > You have to specify the COM port the controller is connected on.
> > 
> > 
> > i have similar problem it said this
> > Traceback (most recent call last):
> > File "C:\Users\deboi\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in
> > import serial, pyvjoy, argparse
> > ModuleNotFoundError: No module named 'serial'
> 
> Did you run `pip install` in the directory to install requirements?

Bruh theres no pip install and it dosent work

**Comment by dekid69** [comment]
> > > You have to specify the COM port the controller is connected on.
> > 
> > 
> > i have similar problem it said this
> > Traceback (most recent call last):
> > File "C:\Users\deboi\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in
> > import serial, pyvjoy, argparse
> > ModuleNotFoundError: No module named 'serial'
> 
> Did you run `pip install` in the directory to install requirements?

yes i have now it said
= RESTART: C:\Users\beanz\Downloads\miniDjiController-master\miniDjiController-master\main.py
Traceback (most recent call last):
  File "C:\Users\beanz\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in <module>
    import serial, pyvjoy, argparse
ModuleNotFoundError: No module named 'pyvjoy'

**Comment by K177ok** [comment]
I think I got it. It was necessary to write pip install until everything that is needed is installed. But there was no information about it anywhere... I prescribed
>pip install serial and other, but:

C:\Users\k177o\Desktop\DJI SIM\MiniDJIController>python main.py
Traceback (most recent call last):
  File "C:\Users\k177o\Desktop\DJI SIM\MiniDJIController\main.py", line 6, in <module>
    import serial, pyvjoy, argparse
  File "C:\Users\k177o\AppData\Local\Programs\Python\Python312\Lib\site-packages\serial\__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "C:\Users\k177o\AppData\Local\Programs\Python\Python312\Lib\site-packages\serial\utilities\__init__.py", line 5, in <module>
    compatibility.backport()  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\k177o\AppData\Local\Programs\Python\Python312\Lib\site-packages\serial\utilities\compatibility.py", line 28, in backport
    exec(BACKWARDS_COMPATIBILITY_IMPORTS, frame.f_globals, frame.f_locals)
  File "<string>", line 4, in <module>
  File "C:\Users\k177o\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

C:\Users\k177o\Desktop\DJI SIM\MiniDJIController>

**Comment by K177ok** [comment]
Oh, it worked! And how could I guess that there was still a lot to install) The problem now is the following, if you run from cmd, you can specify the port, but the delay is VERY large. And if you just run the main file, then it immediately closes. Is it possible to register the port directly in the file and where?

**Comment by henrio6** [comment]
> Oh, it worked! And how could I guess that there was still a lot to install) The problem now is the following, if you run from cmd, you can specify the port, but the delay is VERY large. And if you just run the main file, then it immediately closes. Is it possible to register the port directly in the file and where?

Do you mean the controller input delay? Or startup delay?
