### ISSUE TITLE
does this work on mac? gettin errors

### ISSUE THREAD

**Issue by noahzho** [hjstn/miniDjiController#7]
Traceback (most recent call last):
  File "/Users/noah.zhou/Documents/djiminicontroller.py", line 8, in <module>
    import serial, pyvjoy, argparse
  File "/Users/noah.zhou/Library/Python/3.8/lib/python/site-packages/pyvjoy/__init__.py", line 8, in <module>
    import pyvjoy._sdk
  File "/Users/noah.zhou/Library/Python/3.8/lib/python/site-packages/pyvjoy/_sdk.py", line 8, in <module>
    from ctypes import wintypes	# Makes this lib work in Python36
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

**Comment by henrio6** [comment]
No, this project is currently windows-only
